site_name: 我的个人博客
site_description: 开源软件开发课程实践 - 个人博客
site_author: 王子轩

theme:
  name: material
  palette:
    primary: blue
    accent: indigo

nav:
  - 首页: index.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
